[package]
name = "meadowlark"
version = "0.1.0"
authors = ["Billy Messenger <BillyDM@tutamail.com>"]
edition = "2018"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rusty-daw-io = { git = "https://github.com/RustyDAW/rusty-daw-io", rev = "e67441ad100ca6d629a1324835ecdc7b2ec5478e" }
cpal = "0.13.3"
rusty-daw-time = { git = "https://github.com/RustyDAW/rusty-daw-time.git", rev = "86d97fbab32aa41a9e7e10fd3f8fa75042c80131" }
# tuix = { git = "https://github.com/geom3trik/tuix.git", rev = "5857ba75f7c6793b1e074d4f53746eb0a23b8bda" }
eframe = "0.13.1"
audio-graph = { git = "https://github.com/m-hilgendorf/audio-graph.git", rev = "cb66edcb9901e85a82798b1664ecfddf3ea01038" }
ringbuf = "0.2.5"
basedrop = "0.1.2"
llq = "0.1.1"
fnv = "1.0.7"
atomic_refcell = "0.1.7"
smallvec = "1.6.1"
num-traits = "0.2.14"
symphonia = { version = "0.3.0", features = ["mp3", "aac", "isomp4"] }
log = "0.4"
simple_logger = "1.11"