[package]
name = "meadowlark"
version = "0.1.0"
authors = ["Billy Messenger <BillyDM@tutamail.com>"]
edition = "2021"
license = "GPL-3.0"


[dependencies]
vizia = {git = "https://github.com/vizia/vizia", branch = "main", features = ["serde"]}
meadowlark-core-types = { git = "https://github.com/MeadowlarkDAW/meadowlark-core-types", branch = "main" }
dropseed = { git = "https://github.com/MeadowlarkDAW/dropseed.git", rev = "e1bff7e943c2aaf18020397420db7aec24e185b1" }
#dropseed = { path = "../dropseed" }
log = "0.4"
fast_log = "1.5"
basedrop = "0.1"
crossbeam = "0.8"
rtrb = "0.2"
cpal = "0.13"
fnv = "1.0"
smallvec = "1.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rfd = "0.9"


# Enable this when we're ready to ship.
#[profile.release]
#lto = true

[profile.dev.package.vizia_core]
opt-level = 2
[profile.dev.package.vizia_winit]
opt-level = 2
[profile.dev.package.femtovg]
opt-level = 2
