[package]
name = "meadowlark"
version = "0.1.0"
authors = ["Billy Messenger <BillyDM@tutamail.com>"]
edition = "2018"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rusty-daw-io = { git = "https://github.com/RustyDAW/rusty-daw-io", rev = "e67441ad100ca6d629a1324835ecdc7b2ec5478e" }
cpal = "0.13"
rusty-daw-time = { git = "https://github.com/RustyDAW/rusty-daw-time.git", rev = "c56bf8a7c130893ce3c3745473b15c24e6c1c8a5" }
tuix = { git = "https://github.com/geom3trik/tuix.git", branch = "reactive" }
# tuix = { path = "../tuix" }
# audio-graph = { git = "https://github.com/m-hilgendorf/audio-graph.git", rev = "cb66edcb9901e85a82798b1664ecfddf3ea01038" }
audio-graph = { path = "../audio-graph" }
ringbuf = "0.2"
basedrop = "0.1"
llq = "0.1"
fnv = "1.0"
twox-hash = "1.6"
atomic_refcell = "0.1"
smallvec = "1.6"
num-traits = "0.2"
symphonia = { version = "0.3", features = ["mp3", "aac", "isomp4"] }
log = "0.4"
simple_logger = "1.11"